blank_issues_enabled: false
contact_links:
  - name: 📚 DigiNativa Documentation
    url: https://github.com/jhonnyo88/multi-agent-setup/blob/main/README.md
    about: Läs mer om projektet och AI-teamet
  - name: 🤖 AI-Team Status Dashboard
    url: https://github.com/jhonnyo88/multi-agent-setup/projects
    about: Se vad AI-teamet arbetar på just nu
  - name: 💬 Diskussioner & Frågor
    url: https://github.com/jhonnyo88/multi-agent-setup/discussions
    about: Allmänna frågor och diskussioner om DigiNativa
  - name: 🔧 Teknisk Support
    url: https://github.com/jhonnyo88/multi-agent-setup/wiki
    about: Teknisk dokumentation och troubleshooting