name: 🐛 Bug Report (AI-Team)
description: Report a bug that our AI team will investigate and fix
title: "[BUG] "
labels: ["bug", "ai-team", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## AI-Team Bug Investigation
        
        Our AI quality assurance team will investigate this bug:
        
        - **🔍 QA-Testare** analyzes from user perspective
        - **⚡ Kvalitetsgranskare** checks for technical issues
        - **💻 Utvecklare** identifies and fixes the problem
        - **🧪 Testutvecklare** prevents regression
        
        Please provide detailed information to help us reproduce and fix the issue quickly!

  - type: input
    id: bug_summary
    attributes:
      label: Bug Summary
      description: Brief description of the problem
      placeholder: "Progress dashboard shows incorrect completion percentage"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severely does this impact the user experience?
      options:
        - 🚨 Critical (app unusable, data loss, security issue)
        - 🔥 High (major feature broken, significant UX impact)
        - ⚠️ Medium (feature partially working, minor UX issues)  
        - ℹ️ Low (cosmetic issues, edge cases)
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to recreate the bug
      placeholder: |
        1. Log in as Anna (public sector user)
        2. Navigate to progress dashboard
        3. Complete one learning module
        4. Refresh the page
        5. Observe incorrect percentage shown
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "Progress should show 25% completion after finishing one of four modules"
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior  
      description: What actually happens?
      placeholder: "Progress shows 0% completion despite completing module"
    validations:
      required: true

  - type: dropdown
    id: user_type
    attributes:
      label: Affected User Type
      description: Which user persona experiences this bug?
      options:
        - Anna (Offentlig förvaltare - primary user)
        - Erik (IT-chef - technical user)
        - Margareta (Kommunchef - decision maker)
        - David (Handläggare - frontline user)
        - All user types
        - Unknown/Not specific
    validations:
      required: true

  - type: checkboxes
    id: design_principles_impacted
    attributes:
      label: Design Principles Impact
      description: Which design principles does this bug violate?
      options:
        - label: "🎓 **Pedagogik Framför Allt** - Impacts learning effectiveness"
        - label: "🌉 **Policy till Praktik** - Breaks practical application"
        - label: "⏰ **Respekt för Tid** - Wastes user's time or creates delays"
        - label: "🔗 **Helhetssyn** - Breaks system understanding"
        - label: "🎯 **Intelligens** - Makes system seem unreliable/unprofessional"

  - type: input
    id: environment_browser
    attributes:
      label: Browser & Version
      description: Which browser and version?
      placeholder: "Chrome 119.0.6045.105, Firefox 119.0, Safari 17.0"
    validations:
      required: true

  - type: input
    id: environment_os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: "Windows 11, macOS Sonoma 14.1, Ubuntu 22.04"
    validations:
      required: true

  - type: dropdown
    id: device_type
    attributes:
      label: Device Type
      description: What device are you using?
      options:
        - Desktop/Laptop
        - Mobile Phone
        - Tablet
        - Multiple devices (describe in additional info)
    validations:
      required: true

  - type: textarea
    id: console_errors
    attributes:
      label: Console Errors (if any)
      description: Check browser developer tools (F12) for any error messages
      placeholder: |
        Open browser dev tools (F12), go to Console tab, reproduce the bug, then copy any error messages here.
        
        Example:
        TypeError: Cannot read property 'progress' of undefined
        at ProgressDashboard.jsx:42

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Screenshots, network conditions, or other relevant details
      placeholder: |
        - Screenshots or screen recordings
        - Network connection quality (slow/fast/intermittent)
        - Frequency (always happens / sometimes / rarely)
        - Workarounds you've found
        - Related issues or patterns

  - type: markdown
    attributes:
      value: |
        ---
        
        ## Bug Fixing Process
        
        1. **Triage** - QA team prioritizes based on severity and impact
        2. **Investigation** - AI agents analyze logs and reproduce issue
        3. **Root Cause Analysis** - Technical team identifies underlying problem
        4. **Fix Development** - Code solution with proper testing
        5. **Quality Assurance** - Verify fix and prevent regression
        6. **Deployment** - Release fix to production
        
        **Expected resolution time:**
        - 🚨 Critical: Within 24 hours
        - 🔥 High: 2-3 days  
        - ⚠️ Medium: 1 week
        - ℹ️ Low: Next maintenance cycle
        
        Thank you for helping us improve DigiNativa's quality! 🐛➡️✨