blank_issues_enabled: false
contact_links:
  - name: 📖 DigiNativa Project
    url: https://github.com/jhonnyo88/diginativa-game
    about: Main project repository where features are created
  - name: 💼 Project Management
    url: https://github.com/jhonnyo88/diginativa-game/issues
    about: Create features and track project progress
  - name: 💬 Community Discussions
    url: https://github.com/jhonnyo88/multi-agent-setup/discussions
    about: Technical discussions about AI team setup
  - name: 🚀 AI Team Status Dashboard
    url: https://github.com/jhonnyo88/multi-agent-setup/actions
    about: Internal AI team coordination status