blank_issues_enabled: false
contact_links:
  - name: 📖 DigiNativa Documentation
    url: https://github.com/jhonnyo88/multi-agent-setup/blob/main/README.md
    about: Read our comprehensive setup and usage guide
  - name: 💬 Community Discussions
    url: https://github.com/jhonnyo88/multi-agent-setup/discussions
    about: Ask questions and share experiences with other AI team builders
  - name: 🚀 AI Team Status Dashboard
    url: https://github.com/jhonnyo88/multi-agent-setup/actions
    about: Check current status of our AI development team
  - name: 📊 Project Roadmap
    url: https://github.com/jhonnyo88/multi-agent-setup/projects
    about: See what features are planned and in development