name: 📋 Story Breakdown (AI-Team Internal)
description: Internal template for breaking down features into implementable stories
title: "[STORY] "
labels: ["story", "internal", "ai-coordination"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🤖 AI-Team Internal Coordination
        
        This template is used by our Projektledare agent to break down features into stories.
        Regular users should use the **Feature Request** template instead.

  - type: input
    id: parent_feature
    attributes:
      label: Parent Feature Issue
      description: Link to the original feature request
      placeholder: "#123 - Add user progress tracking"
    validations:
      required: true

  - type: textarea
    id: story_description
    attributes:
      label: Story Description
      description: What does this specific story deliver?
      placeholder: "Create React component for progress visualization"
    validations:
      required: true

  - type: dropdown
    id: assigned_agent
    attributes:
      label: Assigned AI Agent
      description: Which specialist agent will handle this story?
      options:
        - Speldesigner (Game mechanics & UX)
        - Utvecklare (React + FastAPI implementation)
        - Testutvecklare (Automated testing)
        - QA-Testare (User perspective testing)
        - Kvalitetsgranskare (Performance & quality)
    validations:
      required: true

  - type: dropdown
    id: story_type
    attributes:
      label: Story Type
      description: What type of work is this?
      options:
        - specification (Design & UX specification)
        - frontend (React component development)
        - backend (FastAPI endpoint development)
        - testing (Automated test creation)
        - qa (Manual testing & validation)
        - quality_review (Performance & architectural review)
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Specific, testable criteria for this story
      placeholder: |
        - [ ] Component renders progress percentage correctly
        - [ ] Responsive design works on mobile
        - [ ] Loads data in <500ms
        - [ ] Accessible (WCAG compliance)
      value: |
        - [ ] 
        - [ ] 
        - [ ]
    validations:
      required: true

  - type: dropdown
    id: estimated_effort
    attributes:
      label: Estimated Effort
      description: How much work is this story?
      options:
        - Small (2-4 hours)
        - Medium (1-2 days)
        - Large (3+ days)
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Other stories or external requirements needed first
      placeholder: "Depends on: STORY-123 (User authentication backend)"

  - type: checkboxes
    id: design_principles_addressed
    attributes:
      label: Design Principles Addressed
      description: Which principles does this story support?
      options:
        - label: "🎓 Pedagogik Framför Allt"
        - label: "🌉 Policy till Praktik"  
        - label: "⏰ Respekt för Tid"
        - label: "🔗 Helhetssyn"
        - label: "🎯 Intelligens, Inte Infantilisering"

  - type: textarea
    id: technical_notes
    attributes:
      label: Technical Implementation Notes
      description: Specific guidance for the assigned agent
      placeholder: |
        - Use React hooks for state management
        - Implement lazy loading for performance
        - Follow existing component patterns
        - Ensure TypeScript compatibility